# Generated by Django 3.2.7 on 2021-10-12 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_customer_discount_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'مشتری', 'verbose_name_plural': 'مشتری ها'},
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
