# Generated by Django 3.2.7 on 2021-09-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
