# Generated by Django 3.2.7 on 2021-09-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_alter_basket_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.IntegerField(choices=[(1, 'ready'), (2, 'sent'), (3, 'delivered')], default=1),
        ),
    ]
