# Generated by Django 3.2.7 on 2021-09-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('basket', '0004_delete_orderhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='customers',
            field=models.ManyToManyField(null=True, to='members.Customer'),
        ),
    ]
