# Generated by Django 3.2.7 on 2021-10-11 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.address'),
        ),
    ]
