# Generated by Django 3.2.7 on 2021-10-12 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_auto_20211011_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبد های خرید'},
        ),
    ]
