# Generated by Django 3.2.7 on 2021-10-12 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20211012_1013'),
        ('members', '0003_auto_20211012_1013'),
        ('basket', '0010_alter_basket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس ها'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'کد تخفیف', 'verbose_name_plural': 'کد های تخفیف '},
        ),
        migrations.AlterField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.customer', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.customer', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='final_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت نهایی'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='product',
            field=models.ManyToManyField(null=True, to='products.Product', verbose_name='محصولات'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.IntegerField(choices=[(1, 'ready'), (2, 'sent'), (3, 'delivered')], default=1, verbose_name='وضعیت پردازش'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='مجموع قیمت'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_number',
            field=models.PositiveIntegerField(verbose_name='کد تخفیف'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='customers',
            field=models.ManyToManyField(null=True, to='members.Customer', verbose_name='مشتری ها'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انتقضا'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
    ]
