# Generated by Django 3.2.7 on 2021-09-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
