# Generated by Django 3.2.7 on 2021-09-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='order_number',
        ),
    ]
